CREATE DATABASE IF NOT EXISTS stm_db;

CREATE TABLE IF NOT EXISTS users (
  userId INTEGER NOT NULL PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  lastName VARCHAR(64) NOT NULL,
  email VARCHAR(64) NOT NULL,
  pass VARCHAR(64) NOT NULL,
  status BIT(1) NOT NULL,
  registration DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
  taskId INTEGER NOT NULL PRIMARY KEY,
  title VARCHAR(64) NOT NULL,
  description VARCHAR(64) NOT NULL,
  dateAdded DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  type ENUM ('TASK', 'BUG', 'FEATURE'),
  status ENUM ('NEW', 'IN_PROGRESS', 'DONE')
);
